import React from 'react'
import './globals.scss'
import Navbar from '../components/navbar/main'

export const metadata = {
  title: 'A Travel Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-neutral-100 to-pink-200 min-h-screen">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
