import React from 'react'
import './globals.scss'

export const metadata = {
  title: 'My Travel Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-neutral-100 to-pink-200">{children}</body>
    </html>
  )
}
